@startuml
' Diagramme UML des classes du projet FlappyBird

class GameView {
    "constuctor" GameView(context: Context, attributes: AttributeSet?, defStyleAttr: Int)
    - thread: Thread
    - drawing: Boolean
    - canvas: Canvas
    - allObjects: AllObjects
    - gameRun: GameRun
    - gameDisplay: GameDisplay

    + run()
    + pause()
    + resume()
    + onTouchEvent(event: MotionEvent?): Boolean
}

class AllObjects {
    "constuctor" AllObjects (context: Context, var canvas: Canvas, holder: SurfaceHolder)
    + bird: Bird
    + ListOfPipes: MutableList<Pipe>()
    + score: Score
    - scoreObserver: ScoreObserver
}

class GameRun {
    "constuctor" GameRun(private val allObjects: AllObjects)
    - previousFrameTime: Long
    - gameMode: PipeType

    -gameOver()
    -returnEndGame():Boolean
    -createPipe()
    + setTime()
    + run()
}

class GameDisplay {
    "constuctor" GameDisplay(val allObjects : AllObjects)
    - paint: Paint

    + draw()
}

abstract class GameObject {
    "constuctor" GameObject(var x: Float, var y: Float, protected var width: Float, protected var height: Float)

    + update(time: Int)
    + returnCollision(obstacle: Obstacle): Boolean
}

class Bird {
    "constuctor" Bird(x: Float, y: Float)
    + ascendingState: Boolean
    + oldY: Float
    - gravity: Float
    - jumpPower: Float
    - offsetHitbox: Float

    -updateHitBox()
    + update(time: Int)
    + draw(canvas: Canvas, paint: Paint)
}

class Score {
    + yourScore: Int
    - textPaint: Paint
    - observers: MutableList<GameObserver>

    + update(t: Int)
    + draw(canvas: Canvas, paint: Paint)
    + addObserver(observer: GameObserver)
    + removeObserver(observer: GameObserver)
    + notifyObservers()
    + clearObservers()
}

class ScoreObserver {
    "constuctor" ScoreObserver(private val context: Context)
    - mediaPlayer: MediaPlayer

    + onScoreChanged(score: Int)
    + onGameOver()
    - playSound()
}

abstract class Obstacle {
    + allShapesForOneObstacle: ArrayList<RectF>
    - paint: Paint
    # color: Int

    + draw(canvas: Canvas)
}

abstract class Pipe {
    + Xpos: Float
    + Ypos: Float
    + width: Float
    # lowerShape: RectF
    # upperShape: RectF
    # pipeSpeedY: Float
    # pipeSpeedX: Float
}

class HorizontalPipe {
    - lenght: Float
    - opening: Float

    + update()
}

class PipeMoving {
    - upperShapeHeight: Float
    - inverter: Float

    + update()
}

class StaticPipe {
    - upperShapeHeight

    + update()
}

class SkinManager {
    - skinColors: List<Int>
    - selectedIndex: Int

    + getSkin(index: Int)
    + getCurrentColor(): Int
    + getAvailableColor(): List<Int>
    + getCurrentIndex(): Int
}

class GameStateManager {
    - currentState: GameState

    + updateState(score: Int)
    + getPipeType(): PipeType
}

class EasyState {
    + getPipeType(): PipeType
}

class MediumState {
    + getPipeType(): PipeType
}

class HardState {
    + getPipeType(): PipeType
}


interface Drawable {
    + draw(canvas: Canvas)
}

interface Updatable {
    + update()
}

interface Observable {
    + addObserver(observer: GameObserver)
    + removeObserver(observer: GameObserver)
    + notifyObservers()
}

interface GameObserver {
    + onScoreChanged(score: Int)
    + onGameOver()
}

interface GameState {
    + getPipeType(): PipeType
}

' Relations entre les classes et interfaces
GameView --> AllObjects
GameView --> GameRun
GameView --> GameDisplay
AllObjects --> Bird
AllObjects --> Score
AllObjects --> Obstacle
AllObjects --> ScoreObserver
GameObject <|-- Bird
GameObject <|-- Score
Obstacle <|-- HorizontalPipe
Obstacle <|-- Pipe
Obstacle <|-- PipeMoving
Obstacle <|-- StaticPipe
GameObject ..|> Drawable
Obstacle ..|> Drawable
Obstacle ..|> Updatable
Bird ..|> Updatable
ScoreObserver --> GameObserver
Score ..|> Observable
GameStateManager --> GameState
GameState <|-- EasyState
GameState <|-- MediumState
GameState <|-- HardState

@enduml